[package]
name = "agusmirand9/mano-app"
version = "0.1.17"
description = "Mano a Mano"

[dependencies]
"php/php" = "^8.3.1"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]
